#!/bin/bash

set -o errexit

APT_PACKAGES='
  git
  gnome-tweaks
  vim
'

SSH_KEY_FILE="$HOME/.ssh/id_rsa"

SYMLINK_FILES='
  .bash_aliases
  .bash_prompt
  .bashrc
  .gitconfig
  .vimrc
'

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

script_file="$(basename "$0")"
log_file="$script_file.log"

if [ "$1" = '-v' ]; then
  verbose='true'
fi

main() {
  create_log_file
  install_apt_packages
  symlink_files
  create_ssh_keys
}

create_log_file() {
  echo "creating log file $log_file"
  > "$log_file"
}

install_apt_packages() {
  echo 'updating apt'
  sudo apt-get update >> "$log_file"

  echo 'upgrading apt packages'
  sudo apt-get upgrade --yes >> "$log_file"
  
  for package in $APT_PACKAGES; do
    if [ ! "$(is_apt_package_installed "$package")" ]; then
      echo "installing $package"
      sudo apt-get install --yes "$package" >> "$log_file"
    else
      debug "$package already installed"
    fi
  done
}

symlink_files() {
  for file in $SYMLINK_FILES; do
    if [ ! -h "$HOME/$file" ]; then
      if [ -e "$HOME/$file" ]; then
        echo "backing up original $file"
        mv "$HOME/$file" "$HOME/$file.bak"
      fi
      echo "symlinking $file"
      ln --symbolic "$script_dir/$file" "$HOME"
    else
      debug "$file already symlinked"
    fi
  done
}

create_ssh_keys() {
  if [ ! -e "$SSH_KEY_FILE" ]; then
    echo 'creating ssh keys'
    ssh-keygen -f "$SSH_KEY_FILE" -N '' > /dev/null
  else
    debug 'ssh keys already created'
  fi
}

debug() {
  local message="$1"
  if [ "$verbose" ]; then
    echo "$message"
  fi
}

is_apt_package_installed() {
  local package="$1"
  dpkg --get-selections | grep "$package\s" > /dev/null
  if [ $? -eq 0 ]; then
    echo 'true'
  fi
}

main
