#!/bin/bash

set -o errexit
set -o verbose

# apt packages
sudo apt-get update
sudo apt-get upgrade --yes
sudo apt-get autoremove --yes
sudo add-apt-repository multiverse  # for steam
sudo apt-get install --yes steam

# snap packages
sudo snap refresh
sudo snap install minecraft 

