#!/bin/bash

set -o errexit
set -o verbose

cd ~

if [ ! -h .bashrc ]; then
  mv .bashrc .bashrc.bak
fi

ln --force --symbolic projects/dotfiles/.bash_aliases
ln --force --symbolic projects/dotfiles/.bash_prompt
ln --force --symbolic projects/dotfiles/.bashrc
ln --force --symbolic projects/dotfiles/.gitconfig
ln --force --symbolic projects/dotfiles/.vimrc
