#!/bin/bash

set -o errexit
set -o verbose

# apt 
sudo apt-get update
sudo apt-get upgrade --yes
sudo apt-get autoremove --yes
sudo apt-get install --yes gdebi-core  # for chrome
sudo apt-get install --yes gnome-tweaks
sudo apt-get install --yes nautilus-dropbox
sudo apt-get install --yes vim
if [ $1 = '--games' ]; then
  sudo add-apt-repository multiverse  # for steam
  sudo apt-get install --yes steam
fi

# snap
sudo snap refresh
sudo snap install pycharm-professional --classic
sudo snap install spotify
if [ $1 = '--games' ]; then
  sudo snap install minecraft
fi

# chrome
if [ -z "$(dpkg --list google-chrome-stable 2> /dev/null)" ]; then
  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  sudo gdebi --non-interactive google-chrome-stable_current_amd64.deb
  rm google-chrome-stable_current_amd64.deb
fi

